version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
#    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "online_wallet"
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  online-wallet:
    image: hoholms/online-wallet:1.4
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
#    restart: always
    environment:
      PORT: 8080
      HOSTNAME: "localhost:8888"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_NAME: "online_wallet"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    networks:
      backend:
        aliases:
          - "online-wallet"

networks:
  backend:
    driver: bridge
